#!/bin/sh
scripts=$(readlink -f "`dirname $0`/..")

# Include bin folder
export PATH="$PATH:$scripts/bin"

# Include git shortcuts
source "$scripts/shell/git"

# Include bash_shortcuts
source "$scripts/shell/shortcuts"

# Set micro as default editor
export VISUAL=micro
export EDITOR=micro

# ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
export CCACHE_DIR=$HOME/ROMs/ccache
