#!/bin/sh

# Retrieve scripts directory
if [ -n "${BASH_SOURCE}" ]; then
  scripts=$(readlink -f "`dirname ${BASH_SOURCE[0]}`/..")
else
  scripts=$(readlink -f "`dirname $0`/..")
fi

# Include bin folder
export PATH="$PATH:$scripts/bin"

# Include git shortcuts
source "$scripts/shell/git"

# Include bash_shortcuts
source "$scripts/shell/shortcuts"

# Set micro as default editor
export VISUAL=micro
export EDITOR=micro

# ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
export CCACHE_DIR=$HOME/ROMs/ccache
