#!/bin/sh

function merge_log() {
	remote=${1};
	tag=${2};
	git fetch $remote $tag
	git merge FETCH_HEAD -m "Merge $tag of $(git remote get-url $remote) into $(git branch | grep "\*" | sed 's/\* //')

$(git log --oneline $(git branch | grep "\*" | sed 's/\* //')..FETCH_HEAD)" --signoff
};

alias commit='git commit'
alias amend='git commit --amend'
alias pick='git cherry-pick'
alias add='git add -A'
alias rebase='git rebase'
