#!/bin/sh

function launch_python2() {
	virtualenv2 venv && source venv/bin/activate && export LC_ALL=C
};

add_gerrit() {
	while [[ $# -ge 1 ]]; do
		case "${1}" in

		"-r" | "--repo")
			shift
			git remote add gerrit ssh://DD3Boh@review.lineageos.org:29418/LineageOS/${1}
			;;

		"-h" | "--help")
			shift

			echo "-r | --repo    -    chose the repo name"
			echo "-R | --rom     -    chose the rom between lineage and TWRP"
			echo "-h | --help    -    show this help";;

		*)
			shift

			echo "Invalid option ${1}";
			git remote remove gerrit;;

		esac

		shift
	done
};

fast_gerrit() {
	case "${1}" in
		"lineage" | "Lineage" | "LineageOS" | "lineageos")
			shift

			scp -p -O -P 29418 DD3Boh@review.lineageos.org:hooks/commit-msg .git/hooks;
			amend --no-edit;;
	esac;
};

push_gerrit() {
	git push gerrit HEAD:refs/for/${1}
};

dec_dtb() {
	if [[ ${1} == '--help' ]]; then
		echo "Usage: dec_dtb <output>.dts <input>.dtb"
		return 0
	fi;
	dtc -I dtb -O dts -o ${1} ${2}
};

backup_branch() {
	if [[ ${1} == "" ]]; then
		return 0;
	fi;
	remote=${1}
	current_branch=$(git branch --show-current)
	current_date=$(date +%G%m%d)
	backup_branch=backup/$current_branch-$current_date
	git checkout -b $backup_branch
	git fetch $remote $current_branch
	git reset --hard FETCH_HEAD
	git checkout $current_branch
};

savedefconfig() {
	if [[ -z $(ls arch/*/configs/${1}_defconfig) ]]; then
		defconfig="vendor/${1}_defconfig"
	else
		defconfig="${1}_defconfig"
	fi;
	make O=../out/${1} $defconfig ARCH=arm64
	make savedefconfig ARCH=arm64 O=../out/${1}
	cp ../out/${1}/defconfig arch/arm64/configs/$defconfig
};

bootwindows() {
	sudo bootctl set-oneshot auto-windows
	reboot
}

# HIstory SEarch (hise)
hise() { fc -lim "*$@*" 1 }

# Aliases
alias sideload='adb shell twrp sideload; adb wait-for-sideload; adb sideload'
alias blocker='nohup distraction-blocker > /dev/null 2>&1 &; disown'
