#!/bin/sh

function launch_python2() {
	virtualenv2 venv && source venv/bin/activate && export LC_ALL=C
};

add_gerrit() {
	while [[ $# -ge 1 ]]; do
		case "${1}" in

		"-r" | "--repo")
			shift

			repo="${1}";;

		"-R" | "--rom")
			shift

			case "${1}" in

			"lineage" | "Lineage" | "LineageOS" | "lineageos")
				shift

				git remote add gerrit ssh://DD3Boh@review.lineageos.org:29418/LineageOS/$repo;;

			"twrp" | "TWRP")
				shift

				git remote add gerrit ssh://DD3Boh@gerrit.twrp.me:29418/$repo;;

			*)
				shift

				echo "Invalid ROM";;

			esac;;

		"-h" | "--help")
			shift

			echo "-r | --repo    -    chose the repo name"
			echo "-R | --rom     -    chose the rom between lineage and TWRP"
			echo "-h | --help    -    show this help";;

		*)
			shift

			echo "Invalid option ${1}";
			git remote remove gerrit;;

		esac

		shift
	done
};

fast_gerrit() {
	case "${1}" in
		"lineage" | "Lineage" | "LineageOS" | "lineageos")
			shift

			scp -p -P 29418 DD3Boh@review.lineageos.org:hooks/commit-msg .git/hooks;
			amend --no-edit;;

		"twrp" | "TWRP")
			shift

			scp -p -P 29418 DD3Boh@gerrit.twrp.me:hooks/commit-msg .git/hooks;
			amend --no-edit;;
	esac;
};

push_gerrit() {
	git push gerrit HEAD:refs/for/${1}
};

dec_dtb() {
	if [ ${1} == '--help' ]; then
		echo "Usage: dec_dtb <output>.dts <input>.dtb"
		return 0
	fi;
	dtc -I dtb -O dts -o ${1} ${2}
};

backup_branch() {
	if [[ ${1} == "" ]]; then
		return 0;
	fi;
	remote=${1}
	current_branch=$(git branch --show-current)
	current_date=$(date +%G%m%d)
	backup_branch=backup/$current_branch-$current_date
	git checkout -b $backup_branch
	git fetch $remote $current_branch
	git reset --hard FETCH_HEAD
	git checkout $current_branch
};
