#!/bin/bash

function checkout_vendor() {
	commit=$(git status | grep "You are currently cherry-picking commit" | awk '{print $6}' | sed 's/\.//');
	for i in $(git status | grep "both modified" | awk '{print $3}'); do git checkout $commit -- $i; done
};

function checkout_head() {
	for i in $(git status | grep "both modified" | awk '{print $3}'); do git checkout HEAD -- $i; done
};

function merge_log() {
	remote=${1};
	tag=${2};
	git fetch $remote $tag
	git merge FETCH_HEAD -m "Merge $tag of $(git remote get-url $remote) into $(git branch | grep "\*" | sed 's/\* //')

$(git log --oneline $(git branch | grep "\*" | sed 's/\* //')..FETCH_HEAD)" --signoff
};

alias commit='git commit'
alias amend='git commit --amend'
alias pick='git cherry-pick'
alias add='git add -A'
